/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CertificadoDigitalRouteImport } from './routes/certificado-digital'
import { Route as IndexRouteImport } from './routes/index'

const CertificadoDigitalRoute = CertificadoDigitalRouteImport.update({
  id: '/certificado-digital',
  path: '/certificado-digital',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/certificado-digital': typeof CertificadoDigitalRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/certificado-digital': typeof CertificadoDigitalRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/certificado-digital': typeof CertificadoDigitalRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/certificado-digital'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/certificado-digital'
  id: '__root__' | '/' | '/certificado-digital'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CertificadoDigitalRoute: typeof CertificadoDigitalRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/certificado-digital': {
      id: '/certificado-digital'
      path: '/certificado-digital'
      fullPath: '/certificado-digital'
      preLoaderRoute: typeof CertificadoDigitalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CertificadoDigitalRoute: CertificadoDigitalRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
